import asyncio
import os
import re
from datetime import date
from pathlib import Path
from typing import Any

import aiosqlite
from pydantic import BaseModel, ConfigDict, Field, ValidationError

from utils.database import AsyncItemRepository
from utils.llm import complete_text_from_stream
from utils.system_message import system_message

SAMPLE_PARAGRAPHS = [
    "Yesterday I logged two expenses: id 1 for Alice amount 1200.50 on March 25, 2026, and id 2 for Bob amount 300 dated 20/03/2026.",
    "Messy note: (#7, Name=Charlie, Rs. 99.95, date: 03-21-2026), invalid one missing amount for Dana, and #8 Eve paid 500 on 2026-03-24.",
    "In this paragraph there are no usable records, just random words and numbers like 42 and 9000.",
    "Tabular style sentence: id: 10 | name: Frank | amount: 15.5 | date: 25/03/2026 ; id: 11 | name: Grace | amount: 42.00 | date: March 22, 2026.",
    "Mixed language style: Record id 20, name Hari, amount 1000.25, date 2026-03-20. Another one id 21 name Isha amount 75 date 03/25/2026.",
]


class RecordModel(BaseModel):
    model_config = ConfigDict(str_strip_whitespace=True)

    id: int = Field(gt=0)
    name: str = Field(min_length=1, max_length=99)
    amount: float
    date: date


def load_dotenv(dotenv_path: str = ".env") -> None:
    path = Path(dotenv_path)
    if not path.exists():
        return

    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue

        key, value = stripped.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


def get_llm_config() -> dict[str, Any]:
    provider = os.getenv("API_PROVIDER", "ollama").strip().lower()

    if provider == "groq":
        model_name = os.getenv("GROQ_MODELNAME", "llama-3.3-70b-versatile")
        api_key = os.getenv("GROQ_API_KEY")
    elif provider == "ollama":
        model_name = os.getenv("OLLAMA_MODELNAME", "llama3.1")
        api_key = os.getenv("OLLAMA_API_KEY")
    else:
        raise ValueError("API_PROVIDER must be either 'groq' or 'ollama'")

    if "YOUR_" in model_name:
        raise ValueError(
            "LLM model appears to be placeholder text. Update backend/.env with real values."
        )

    return {
        "provider": provider,
        "api_key": api_key,
        "model_name": model_name,
    }


def extract_record_array(generated_text: str) -> list[dict[str, Any]]:
    """
    Parse C-style Record records[] output generated by the LLM.
    """
    array_match = re.search(
        r"Record\s+records\[\]\s*=\s*\{(?P<body>.*?)\};",
        generated_text,
        flags=re.DOTALL,
    )

    if not array_match:
        return []

    body = array_match.group("body")
    if not body.strip():
        return []

    record_pattern = re.compile(
        r"\{\s*(?P<id>-?\d+)\s*,\s*\"(?P<name>(?:\\.|[^\"\\])*)\"\s*,\s*"
        r"(?P<amount>-?\d+(?:\.\d+)?)\s*,\s*\"(?P<date>\d{4}-\d{2}-\d{2})\"\s*\}",
        flags=re.DOTALL,
    )

    parsed: list[dict[str, Any]] = []
    for match in record_pattern.finditer(body):
        parsed.append(
            {
                "id": int(match.group("id")),
                "name": bytes(match.group("name"), "utf-8").decode("unicode_escape"),
                "amount": float(match.group("amount")),
                "date": match.group("date"),
            }
        )
    return parsed


def validate_records(raw_records: list[dict[str, Any]]) -> tuple[list[RecordModel], list[str]]:
    valid: list[RecordModel] = []
    errors: list[str] = []

    for idx, record in enumerate(raw_records, start=1):
        try:
            valid.append(RecordModel.model_validate(record))
        except ValidationError as exc:
            errors.append(f"Record #{idx} failed validation: {exc}")

    return valid, errors


async def upload_records_to_db(records: list[RecordModel], db_path: str = "data.db") -> int:
    repo = AsyncItemRepository(db_path=db_path)
    await repo.init()

    inserted_or_updated = 0
    for rec in records:
        try:
            await repo.create(rec.id, rec.name, rec.amount, rec.date)
        except aiosqlite.IntegrityError:
            updated = await repo.update(rec.id, rec.name, rec.amount, rec.date)
            if not updated:
                continue
        inserted_or_updated += 1

    return inserted_or_updated


def run_llm_on_paragraph(paragraph: str) -> str:
    load_dotenv()
    config = get_llm_config()

    try:
        return complete_text_from_stream(
            prompt=paragraph,
            system_message=system_message,
            api_provider=config["provider"],
            api_key=config["api_key"],
            model_name=config["model_name"],
        )
    except RuntimeError as exc:
        raise RuntimeError(
            f"Failed to call provider {config['provider']} with model {config['model_name']}: {exc}"
        ) from exc


async def process_llm_output(generated_text: str, db_path: str = "data.db") -> dict[str, Any]:
    raw_records = extract_record_array(generated_text)
    validated_records, validation_errors = validate_records(raw_records)
    uploaded_count = await upload_records_to_db(validated_records, db_path=db_path)

    return {
        "raw_count": len(raw_records),
        "valid_count": len(validated_records),
        "uploaded_count": uploaded_count,
        "validation_errors": validation_errors,
    }


async def run_examples() -> None:
    for idx, paragraph in enumerate(SAMPLE_PARAGRAPHS, start=1):
        print(f"\n--- Example {idx} ---")
        print(f"Input paragraph: {paragraph}")

        try:
            generated_text = run_llm_on_paragraph(paragraph)
        except Exception as exc:
            print(f"LLM call failed: {exc}")
            continue

        print("LLM output:")
        print(generated_text)

        result = await process_llm_output(generated_text, db_path="data.db")
        print("Processing summary:")
        print(result)


if __name__ == "__main__":
    asyncio.run(run_examples())
